@startuml hello
class Skybox
Engine --> "creates" Scene
Engine --> "creates" View
Engine --> "creates" Camera
Scene -- Skybox
Scene *-- "n" View
View *-- "1" Camera
Scene *-- "n" Entity
Material "1" .. "*" MaterialInstance
Entity --> "n MaterialInstance" MaterialInstance
Entity --> "geometry" VertexBuffer
Entity -->  "geometry" IndexBuffer
@enduml
